# Generated by GitHub Copilot

from django.conf import settings
from django.contrib.auth.hashers import make_password
from django.db import migrations
import sys
import os


TEST_USERS = [
    {
        "username": "admin",
        "password": "123456",
        "is_staff": True,
        "is_superuser": True,
        "nombre": "El Administrador",
        "email": "admin@matacartas.es",
        "puntuacion": 2000,
        "email_verificado": True,
        },
    {
        "username": "cervantes",
        "password": "123456",
        "is_staff": False,
        "is_superuser": False,
        "nombre": "Miguel de Cervantes",
        "email": "cervantes@complutum.es",
        "puntuacion": 1500,
        "email_verificado": True,
        "imagen": "https://upload.wikimedia.org/wikipedia/commons/0/09/Cervantes_J%C3%A1uregui.jpg",
    },
    {
        "username": "quevedo",
        "password": "123456",
        "is_staff": False,
        "is_superuser": False,
        "nombre": "Francisco de Quevedo",
        "email": "quevedo@cr.es",
        "puntuacion": 700,
        "email_verificado": True,
        "imagen": "https://www.biografiasyvidas.com/biografia/q/fotos/quevedo_3.jpg",
    },
    {
        "username": "gongora",
        "password": "123456",
        "is_staff": False,
        "is_superuser": False,
        "nombre": "Luis de Góngora",
        "email": "gongora@cordoba.es",
        "puntuacion": 700,
        "email_verificado": True,
        "imagen": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRF3cgLzG6YGAMSD3--dvCfw1S1nauUQBdmRnnfbRVD8w&s=10",
    },
    {
        "username": "lope",
        "password": "123456",
        "is_staff": False,
        "is_superuser": False,
        "nombre": "Lope de Vega",
        "email": "lope@madrid.es",
        "puntuacion": 600,
        "email_verificado": True,
        "imagen": "https://scenamalaga.com/wp-content/uploads/2024/01/Lope-de-Vega-2.jpg",
    },
    {
        "username": "becquer",
        "password": "123456",
        "is_staff": False,
        "is_superuser": False,
        "nombre": "Gustavo Adolfo Bécquer",
        "email": "becquer@sevilla.es",
        "puntuacion": 500,
        "email_verificado": True,
        "imagen": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Portrait_of_Gustavo_Adolfo_B%C3%A9cquer%2C_by_his_brother_Valeriano_%281862%29.jpg/960px-Portrait_of_Gustavo_Adolfo_B%C3%A9cquer%2C_by_his_brother_Valeriano_%281862%29.jpg",
    },
    {
        "username": "velazquez",
        "password": "123456",
        "is_staff": False,
        "is_superuser": False,
        "nombre": "Diego de Velázquez",
        "email": "velazquez@sevilla.es",
        "puntuacion": 400,
        "email_verificado": True,
        "imagen": "https://historia-arte.com/_/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpbSI6WyJcL2FydGlzdFwvaW1hZ2VGaWxlXC9kaWVnby12ZWxhenF1ZXotYXV0b3JyZXRyYXRvLTQ1LXgtMzgtY20tY29sZWNjaW9uLXJlYWwtYWNhZGVtaWEtZGUtYmVsbGFzLWFydGVzLWRlLXNhbi1jYXJsb3M/tbXVzZW8tZGUtYmVsbGFzLWFydGVzLWRlLXZhbGVuY2lhLmpwZyIsInJlc2l6ZUNyb3AsNDAwLDQwMCxDUk9QX0VOVFJPUFkiXX0.mp__DKfdjxTtOlYE0KQ9zRGjdP0BaQkWTSuA7kqrb8I.jpg",
    },
    {
        "username": "murillo",
        "password": "123456",
        "is_staff": False,
        "is_superuser": False,
        "nombre": "Bartolomé Esteban Murillo",
        "email": "murillo@sevilla.es",
        "puntuacion": 300,
        "email_verificado": True,
        "imagen": "https://explorersevilla.com/wp-content/uploads/2016/08/Bartolome-Esteban-Murillo.png",
    },
    {
        "username": "calderon",
        "password": "123456",
        "is_staff": False,
        "is_superuser": False,
        "nombre": "Calderón de la Barca",
        "email": "calderon@madrid.es",
        "puntuacion": 250,
        "email_verificado": True,
        "imagen": "https://i0.wp.com/insulabaranaria.com/wp-content/uploads/2018/01/calderondelabarca.jpg?fit=960%2C1278&ssl=1",
    },
    {
        "username": "garcilaso",
        "password": "123456",
        "is_staff": False,
        "is_superuser": False,
        "nombre": "Garcilaso de la Vega",
        "email": "garcilaso@toledo.es",
        "puntuacion": 200,
        "email_verificado": True,
        "imagen": "https://images.ecestaticos.com/DJJ3lWDXoH5pPbT-3KikgfGHffI=/0x0:0x0/1200x1200/filters:fill(white):format(jpg)/f.elconfidencial.com%2Foriginal%2Fe47%2F5cf%2Fe5a%2Fe475cfe5a9beb82ca4080b2971e1ab77.jpg",
    },

# PRUEBAS DE EXTREMOS
    {
        "username": "u",
        "password": "123456",
        "is_staff": False,
        "is_superuser": False,
        "nombre": "Usuario Username Corto",
        "email": "u@example.com",
        "puntuacion": 15,
        "email_verificado": True,
    },
    {
        "username": "usuario_con_username_long",
        "password": "123456",
        "is_staff": False,
        "is_superuser": False,
        "nombre": "Usuario Username Largo",
        "email": "usuariousernamemax@example.com",
        "puntuacion": 15,
        "email_verificado": True,
    },
    {
        "username": "usuario_p_min",
        "password": "1",
        "is_staff": False,
        "is_superuser": False,
        "nombre": "Usuario Contra Corta",
        "email": "usuariopmin@example.com",
        "puntuacion": 15,
        "email_verificado": True,
    },
    {
        "username": "usuario_p_max",
        "password": "1234567890123456789012345678901234567890123456789012345678901234",
        "is_staff": False,
        "is_superuser": False,
        "nombre": "Usuario Contra Larga",
        "email": "usuariopmax@example.com",
        "puntuacion": 15,
        "email_verificado": True,
    },
    {
        "username": "usuario_nom_min",
        "password": "123456",
        "is_staff": False,
        "is_superuser": False,
        "nombre": "N",
        "email": "usuarionommin@example.com",
        "puntuacion": 15,
        "email_verificado": True,
    },
    {
        "username": "usuario_nom_max",
        "password": "123456",
        "is_staff": False,
        "is_superuser": False,
        "nombre": "Usuario Nombre Largo Largo Largo La",
        "email": "usuarionommax@example.com",
        "puntuacion": 15,
        "email_verificado": True,
    },
    {
        "username": "usuario_email_min",
        "password": "123456",
        "is_staff": False,
        "is_superuser": False,
        "nombre": "Usuario Correo Corto",
        "email": "u@e",
        "puntuacion": 15,
        "email_verificado": True,
    },
    {
        "username": "usuario_email_max",
        "password": "123456",
        "is_staff": False,
        "is_superuser": False,
        "nombre": "Usuario Correo Largo",
        "email": "usuarioemailmaxmaxmaxmaxmaxmaxmaxmaxmaxmaxmaxmaxmaxmaxmaxmaxmaxmaxmaxmaxmaxmaxmaxmaxmaxmaxmaxmaxmaxmaxmaxmaxmaxmaxmaxmaxmaxmaxmaxmaxmaxmaxmaxmaxmaxmaxmaxmaxmaxmaxmaxmaxmaxmaxmaxmaxmaxmaxmaxmaxmaxmaxmaxmaxmaxmaxmaxmaxmaxmaxmaxmaxmaxmaxmaxmaxma@example.com",
        "puntuacion": 15,
        "email_verificado": True,
    },
    {
        "username": "usuario_puntos_max",
        "password": "123456",
        "is_staff": False,
        "is_superuser": False,
        "nombre": "Usuario Puntuación Máxima",
        "email": "usuariopuntosmax@example.com",
        "puntuacion": 99999999,
        "email_verificado": True,
    },
    {
        "username": "usuario_puntos_min",
        "password": "123456",
        "is_staff": False,
        "is_superuser": False,
        "nombre": "Usuario Puntuación Mínima",
        "email": "usuariopuntosmin@example.com",
        "puntuacion": 0,
        "email_verificado": True,
    },
]

RANGO_SEED = [
    {
        "nombre": "PRINCIPIANTE",
        "color": "gris",
        "puntos_minimos": 50,
        "puntos_maximos": 100,
    },
    {
        "nombre": "EXPERIMENTADO",
        "color": "verde",
        "puntos_minimos": 101,
        "puntos_maximos": 300,
    },
    {
        "nombre": "VETERANO",
        "color": "rojo",
        "puntos_minimos": 301,
        "puntos_maximos": 500,
    },
    {
        "nombre": "Z",
        "color": "morado",
        "puntos_minimos": 501,
        "puntos_maximos": 700,
    },
    {
        "nombre": "MAESTRO",
        "color": "amarillo_naranja",
        "puntos_minimos": 701,
        "puntos_maximos": 1500,
    },
    {
        "nombre": "MAESTRO SUPREMO CELESTIAL",
        "color": "amarillo_dorado",
        "puntos_minimos": 1501,
        "puntos_maximos": 2500,
    },
]


def _get_user_model(apps):
    app_label, model_name = settings.AUTH_USER_MODEL.split(".")
    return apps.get_model(app_label, model_name)


def seed_test_users(apps, schema_editor):
    # Skip seeding when running tests or when explicitly disabled
    if "test" in sys.argv or os.getenv("SKIP_SEED", "0") == "1":
        return

    UserModel = _get_user_model(apps)

    for user_spec in TEST_USERS:
        username = user_spec["username"]
        password = user_spec["password"]

        defaults = {
            "password": make_password(password),
            "is_staff": user_spec["is_staff"],
            "is_superuser": user_spec["is_superuser"],
            "is_active": True,
            "email": user_spec.get("email", ""),
            "nombre": user_spec["nombre"],
            "puntuacion": user_spec.get("puntuacion", 0),
            "imagen": user_spec.get("imagen", ""),
            "email_verificado": user_spec.get("email_verificado", False),
        }

        UserModel.objects.update_or_create(username=username, defaults=defaults)


def seed_rangos(apps, schema_editor):
    # Skip seeding when running tests or when explicitly disabled
    if "test" in sys.argv or os.getenv("SKIP_SEED", "0") == "1":
        return

    Rango = apps.get_model("api", "Rango")
    for rango in RANGO_SEED:
        Rango.objects.update_or_create(nombre=rango["nombre"], defaults=rango)


def unseed_test_users(apps, schema_editor):
    UserModel = _get_user_model(apps)
    usernames = [u["username"] for u in TEST_USERS]
    UserModel.objects.filter(username__in=usernames).delete()


def unseed_rangos(apps, schema_editor):
    Rango = apps.get_model("api", "Rango")
    nombres = [rango["nombre"] for rango in RANGO_SEED]
    Rango.objects.filter(nombre__in=nombres).delete()

class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_test_users, reverse_code=unseed_test_users),
        migrations.RunPython(seed_rangos, reverse_code=unseed_rangos),
    ]
